### ISSUE TITLE
Favored equipment item can't be unequipped from favorites tab.

### ISSUE THREAD

**Issue by TiloBuechsenschuss** [sdenec/tidy5e-sheet#580] opened 2022-09-13 18:36 UTC
As per title. An inventory item that's a favorite can be equipped in the favorite tab. But it then can't be unequipped.
Button appears, but clicking it does nothing.
Installed: Tidy5eSheet 0.6.6, DnD 2.0.2, Foundry 10.285

**Comment by roguedevjake** [comment] 2022-12-09 06:36
Yeah, I wasn't sure if this was intended or not, but it does make things harder to get players to use the equip/unequip system.

**Comment by sdenec** [comment] 2022-12-25 12:45
should be fixed

**Closed by sdenec** 2022-12-25 12:45 UTC
