### ISSUE TITLE
[Feature Request] Collaboration Loot Sheet NPC 5e

### ISSUE THREAD

**Issue by justinthejaguar** [sdenec/tidy5e-sheet#279] opened 2021-03-17 20:01 UTC
My players and I love the work that you have put into tidy5e-sheet.

We tend to use Loot Sheet NPC 5e for merchants and treasure. I am not sure how possible it is, but I was wondering if you could work with the Author of Loot Sheet NPC 5e to bring your aesthetic and functionality to the utility of jopeek's module. My players have mentioned the inconsistency in the sheets, and I thought it would be a neat request.

https://github.com/jopeek/fvtt-loot-sheet-npc-5e

I added the request to Loot Sheet NPC 5e as well:
https://github.com/jopeek/fvtt-loot-sheet-npc-5e/issues/118

**Comment by akrigline** [comment] 2021-03-17 20:31
duplicate of #232

**Comment by sdenec** [comment] 2021-12-06 18:30
I'm going to close this as well - I'm not going to be able to work on this in the forseeable future. Sorry!

**Closed by sdenec** 2021-12-06 18:30 UTC
