### ISSUE TITLE
Doubling of Mechanics/Flavor Text in Tidy5eItemSheet

### ISSUE THREAD

**Issue by MrVauxs** [sdenec/tidy5e-sheet#191] opened 2021-01-08 12:32 UTC
The Tidy5e Item Sheet has this graphical error as described in the title
![image](https://user-images.githubusercontent.com/32039708/104016019-c6225000-51b5-11eb-87bf-5ee2b7483be0.png)

**Comment by sdenec** [comment] 2021-01-08 17:24
That is strange. I had it as a bug at one time but never released that version and fixed it aswell. Also I can't reproduce it. Does it happen on every item - when does it happen? Also are you on the most recent version? 0.4.3 as of this writing.

**Comment by akrigline** [comment] 2021-01-08 21:40
This looks like something that the ddb-importer module is currently struggling with, @MrVauxs does this happen if you select the Core sheet?

**Comment by MrVauxs** [comment] 2021-01-08 21:56
I am normally more descriptive than this, I guess I was in a rush when writing this, sorry.
FoundryVTT 0.7.9
DnD5e System 1.2.2
Does not happen in the Core sheet as the Core sheet doesn't have **Mechanics/Flavor Text**... at all.

Seems to be a conflict with another module but Find the Culprit doesn't want to work with me currently, I'll update this when I find that out.

I do not have any of the D&DB related modules.

**Comment by MrVauxs** [comment] 2021-01-08 22:03
[Forien's Unidentified Items](https://github.com/Forien/foundryvtt-forien-unidentified-items) is the culprit!

Also seems to have a similar issue, again, duplicating stuff in [this issue](https://github.com/Forien/foundryvtt-forien-unidentified-items/issues/29).

**Comment by akrigline** [comment] 2021-01-09 05:09
> [Forien's Unidentified Items](https://github.com/Forien/foundryvtt-forien-unidentified-items) is the culprit!
> 
> Also seems to have a similar issue, again, duplicating stuff in [this issue](https://github.com/Forien/foundryvtt-forien-unidentified-items/issues/29).
> 
> Edit: May or may not be related to [this issue](https://github.com/Forien/foundryvtt-forien-unidentified-items/issues/25) as well, which is yet to be fixed in a Pull Request.

You should uninstall and reinstall this module immediately. That should put you at version 0.2.5, which is a [League stewarded fork](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-unidentified-items). There are some GNARLY incompatibilities in the currently "abandoned" main repository.

I'm glad you found the culprit, and I'm glad it's not related to Tidy.

**Comment by sdenec** [comment] 2021-01-09 14:03
Please follow the instruction of @akrigline 
I'll close this issue - If you should still experience problems please reopen or create a new issue :)

**Closed by sdenec** 2021-01-09 14:03 UTC
