### ISSUE TITLE
Support Exhaustion 1-5 linking to Convenient Effects

### ISSUE THREAD

**Issue by TaakoMagnusen** [sdenec/tidy5e-sheet#436] opened 2021-11-11 15:43 UTC
It seems as though DFreds Convenient Effects is becoming more standard with larger popular modules such as midi-qol (midi-srd now relies on DFreds Convenient Effects). I would like to use the exhaustion linking feature that currently requires CUB with tidy5e.

I tried hacking them in using the CUB Conditions lab and Dynamic Active Effects via the  statusEffect Override Convenient Effects: ____  method that tposney, i tried to replace all the exhaustions as well as Dead and Unconscious by overriding them with Convenient Effects. While Dead and Unconscious on 0 worked fine, the Exhaustion levels did not link properly.

I could apply a CE exhaustion level on the token HUD and it would show up in tidy5e (because the names were the same), but if i applied an exhaustion level in tidy5e it would not show up on the token.

**Comment by kaelad02** [comment] 2022-07-15 00:34
should probably close this as a duplicate of #408

**Closed** 2022-12-25 11:56 UTC
