### ISSUE TITLE
Foundry 0.7.3

### ISSUE THREAD

**Issue by Alexis-Grimm** [sdenec/tidy5e-sheet#103] opened 2020-10-07 02:28 UTC
Are you planning on adding support for foundry 0.7.3 or are you going to be waiting for the next stable release? I'm having some issues where special categories added by other modules in 0.7.3 duplicate themselves, it doesn't really effect usability but it does make everything look weird, but it doesn't occur when using the standard foundry sheets. No pressure, just wanted to see, love your module!

**Comment by sdenec** [comment] 2020-10-07 07:15
Hi, I'd like to wait for a stable release - time management wise. But there is a dev discussion in discord regarding better rolls and tidy5e and magic items that seems to duplicate entries and bloat up the database. It's not a tidy5e-bug per see but the better rolls implementation and changes to the hook-functions in the 0.7 update. As far as I have followed the thread it seems the issue should be resolved with the latest better rolls update. So if you have used my sheet with BR and/or magic items that might be the cause! Let me know if this was indeed the cause :)

**Comment by Alexis-Grimm** [comment] 2020-10-07 10:03
Thanks! Yeah that definitely looks to be the issue, I had posted this before the most recent magic items and better rolls released, thanks for your help!

**Closed** 2020-10-07 11:13 UTC
