### ISSUE TITLE
incompatibility with (Mqol + Dynamic Effects)

### ISSUE THREAD

**Issue by rinnocenti** [sdenec/tidy5e-sheet#69] opened 2020-07-22 19:28 UTC
When tidy is activated, effects from items are not applied to the target / itself.

**Comment by sdenec** [comment] 2020-07-22 20:59
What exactly do you mean? If I set an item, e. g. a dagger to have an effect of +10 to max hp or +10 to an attribute these effects will be applied to whoever carries this item. So unlwaa I'm misunderstanding the issue I can't recreate it.

**Comment by rinnocenti** [comment] 2020-07-22 22:56
Sorry, the problem is a little more complicated.
involves BetterRoll to tell the truth.
but it only happens when tidy is on.

I do a mix between better and Mqol.
better controls my Speed roll (and I leave better on the sheet off) and Mqol operates the clicks within the sheet. (because of removing the unloaded item that only works with Mqol).

But with the better roll disabled to create "clickable items" on the sheet, (and the Mqol enabled to create clickable items on the sheet) tidy ignores the Mqol, making the effects not happen, the items on the sheet understand that for the better this disabled is to use the default, not the Mqol version.

**Comment by rinnocenti** [comment] 2020-07-22 23:01
![image](https://user-images.githubusercontent.com/3178127/88237510-c190cc00-cc55-11ea-97c7-97ea8299f6e5.png)
![image](https://user-images.githubusercontent.com/3178127/88237590-eedd7a00-cc55-11ea-9988-503b7109bf16.png)

In this configuration Tidy sees that Better is not making the Item clickable, but ignores MQol to generate the item clickable, making it with the default click

**Comment by rinnocenti** [comment] 2020-07-22 23:07
If I disable "enable better roll" the speed roll of Mqol, enter, but effects not apply.
![image](https://user-images.githubusercontent.com/3178127/88237981-e89bcd80-cc56-11ea-8ab5-885a08a7023b.png)

**Comment by rinnocenti** [comment] 2020-07-22 23:13
![image](https://user-images.githubusercontent.com/3178127/88238335-c3f42580-cc57-11ea-98c8-cf3bd35ba594.png)
But if I Disable Tidy.. that works

**Comment by sdenec** [comment] 2020-09-08 14:37
I'm going to close this. For me the issue is not present and seemingly others don't have problems using Minor/Midi Qol and Dynamic Effects as well. Nothing came up since you first mentioned it. Sorry!

**Closed by sdenec** 2020-09-08 14:37 UTC
