### ISSUE TITLE
Temporary Max HP is not considered when limiting the current HP anymore

### ISSUE THREAD

**Issue by TyrasNistru** [sdenec/tidy5e-sheet#681] opened 2023-02-05 02:12 UTC
For example, if I put that a character has 90 max HP, and put 10 in the +Max Field, the current HP field could reach 100HP. This is not working anymore, but the overlay in the character avatar shows that it is "wounded" (part of the avatar is colored red):

![Screenshot 2023-02-04 231223](https://user-images.githubusercontent.com/9531350/216797971-e5a29b9c-ab4c-4a99-94c5-7008efcb3092.png)

**Comment by p4535992** [comment] 2023-02-06 22:01
I see what the problem is, but I verified that it has always worked that way even before 2.1.X so I'm not sure what you mean by "This is not working anymore" and i verified the same behaviour with the current standard sheet so maybe this is intentional ?
The correct nehaviour it's seem when you set the "Hp Max Temp" to update the "Hp Temp" field not the "Hp Field" directly for the calculation to work.

**Comment by TyrasNistru** [comment] 2023-02-07 00:58
> I see what the problem is, but I verified that it has always worked that way even before 2.1.X so I'm not sure what you mean by "This is not working anymore" and i verified the same behaviour with the current standard sheet so maybe this is intentional ? The correct nehaviour it's seem when you set the "Hp Max Temp" to update the "Hp Temp" field not the "Hp Field" directly for the calculation to work.

That doesn't make sense at all. Temporary HP doesn't have a cap, and (as it should) ignores the temp max HP field. 

The Temp Max HP field is used for effects like the spell Aid, that increases the max HP in a way that the character can be healed up to that new amount (normal maxHP + tempMaxHP). That doesn't happen with temporary HP. Temporary HP lost is "lost forever", and cannot be healed, only regained by effects that grant temporary HP.

![image](https://user-images.githubusercontent.com/9531350/217120981-2ebf36ad-057f-4758-9a48-be1cbeeb108b.png)

**Comment by sdenec** [comment] 2023-02-07 07:45
The equasion tries to incorporate hp.max aswell as tempMax. Maybe the calculations or values are stroed differently now?
```css
background: linear-gradient(
								-90deg,
								transparent 0%,
								transparent calc(100% - ((100% / ({{#if (eq system.attributes.hp.max 0)}} 1 {{else}} {{system.attributes.hp.max}} {{/if}} + {{#if system.attributes.hp.tempmax}}{{system.attributes.hp.tempmax}}{{else}}0{{/if}} )) * ({{system.attributes.hp.value}} + {{#if system.attributes.hp.temp}}{{system.attributes.hp.temp}}{{else}}0{{/if}})) ),
								 	rgba(0, 200, 0, 0.5) calc(100% - ((100% / ({{#if (eq system.attributes.hp.max 0)}} 1 {{else}} {{system.attributes.hp.max}} {{/if}} + {{#if system.attributes.hp.tempmax}}{{system.attributes.hp.tempmax}}{{else}}0{{/if}} )) * ({{system.attributes.hp.value}} + {{#if system.attributes.hp.temp}}{{system.attributes.hp.temp}}{{else}}0{{/if}})) ),
								 	rgba(0, 200, 0, 0.5) 100%);
```

**Comment by TyrasNistru** [comment] 2023-02-07 12:50
The behavior for the wounded overlay is correct, AFAIK. What isn't is the field for the current HP to not take the tempMax value.

**Comment by TyrasNistru** [comment] 2023-02-07 13:01
> I see what the problem is, but I verified that it has always worked that way even before 2.1.X so I'm not sure what you mean by "This is not working anymore" and i verified the same behaviour with the current standard sheet so maybe this is intentional ? The correct nehaviour it's seem when you set the "Hp Max Temp" to update the "Hp Temp" field not the "Hp Field" directly for the calculation to work.

Unfortunately, I have no way to go back, but I remember that it used to work.

**Comment by sdenec** [comment] 2023-02-07 16:23
> I see what the problem is, but I verified that it has always worked that way even before 2.1.X so I'm not sure what you mean by "This is not working anymore" and i verified the same behaviour with the current standard sheet so maybe this is intentional ? The correct nehaviour it's seem when you set the "Hp Max Temp" to update the "Hp Temp" field not the "Hp Field" directly for the calculation to work.

Okay, there is a different behavior between the default sheet and tidy. Tidy will set any value above max health entered into the current helth field to max health. The default sheet will allow to go beyond that. Eg. max health is 44 hp, tidy can't be above 44, default sheet can be 500.

If +max temp is entered tidy still can't exceed the genereal max hp (eg. 44).

It seems only the token on the canvas respects max temp. You'll get a second health bar and if you have 20/44 health and lets say 20 max temp you can heal for 40 and get 40 so the 24 missing from the regular health plus 16 towards max temp.

If you then open the tidy sheet and change anything regarding health in there the current health will sett itself to the maximum default health (eg. 44) while the default sheet keeps the current hp.

I don't know where the problem in this lies though. I never did any calculations for the fields itself. Maybe that happened when you patched the + and - operators? It seems a fix would be no longer needed (if it is still in place). The default sheet can add and substract values again it seems so tidy should as well?

**Comment by p4535992** [comment] 2023-02-07 22:18
It will be fixed on the next release

**Comment by p4535992** [comment] 2023-02-08 22:46
K try out 0.8.18 i have added a separate module settings for manage both bheaviours

**Comment by p4535992** [comment] 2023-02-09 22:01
Try out 0.8.20 now should work like the default one if i'm not missing some other thing

**Comment by TyrasNistru** [comment] 2023-02-10 00:12
0.8.20 It is working as the default one. That's better, but, why not just limit the current HP in MaxHP + TempMaxHP? Just asking.

**Comment by p4535992** [comment] 2023-02-10 08:41
it's not a problem to put an additional module setting for that... but I would warn you that there are automated modules and spells that increase the lives of the character and if you edit the lives of the character in the sheet with that limitation then they are "lost" and from what I've seen that is something that is not "welcome"

**Comment by TyrasNistru** [comment] 2023-02-11 13:45
> it's not a problem to put an additional module setting for that... but I would warn you that there are automated modules and spells that increase the lives of the character and if you edit the lives of the character in the sheet with that limitation then they are "lost" and from what I've seen that is something that is not "welcome"

I don't see why a module would increase the current HP past the limit (maxHP + tempMaxHP), since, AFAIK, the only way you can do that in the rules is through Temporary HP. 

Regardless, I think that's a good idea to put a setting for this. If someone uses a module that does increase current HP past the limit, then they can just disable the setting.

**Comment by p4535992** [comment] 2023-02-12 10:46
Added a module setting on 0.8.21.

**Closed** 2023-02-16 08:39 UTC
Labels: bug, in discussion, probably fixed
